# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/negfi/Documents/AUT/5thSemester/DigitalDesignAutomation/Phaze4/Phaze4/Phaze4.cache/wt [current_project]
set_property parent.project_path C:/Users/negfi/Documents/AUT/5thSemester/DigitalDesignAutomation/Phaze4/Phaze4/Phaze4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/negfi/Documents/AUT/5thSemester/DigitalDesignAutomation/Phaze4/Phaze4/Phaze4.srcs/sources_1/new/Security.vhd
synth_design -top Security -part xc7vx485tffg1761-2
write_checkpoint -noxdef Security.dcp
catch { report_utilization -file Security_utilization_synth.rpt -pb Security_utilization_synth.pb }
